service: dba-server

frameworkVersion: "^3.39.0"

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1
  memorySize: 256
  timeout: 10
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_OPTIONS: "--enable-source-maps"
    NODE_ENV: ${self:provider.stage}                # ← dentro de environment
    OPENAI_API_KEY: ${ssm:/dba/dev/OPENAI_API_KEY~true}
  httpApi:
    cors:
      # Durante desarrollo, abierto. En prod: reemplaza por tu dominio de GH Pages.
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowCredentials: false                       # ← evita conflicto con "*"

package:
  individually: false
  patterns:
    - "!**/*"
    - dist/lambda.mjs

functions:
  api:
    handler: dist/lambda.handler
    name: dba-api-${self:provider.stage}
    description: "@dba/server Express on Lambda via serverless-http"
    architecture: arm64
    runtime: nodejs20.x
    memorySize: 256
    timeout: 10
    events:
      - httpApi:
          method: ANY                               # ← recomendado en mayúsculas
          path: /{proxy+}
      - httpApi:
          method: GET
          path: /health

plugins: []

custom:
  # Build happens outside via npm script using esbuild; no serverless-esbuild plugin needed
  # Tip: In prod, restrict CORS
