service: dba-server

frameworkVersion: "^3.39.0"

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1
  stage: ${opt:stage, 'dev'}        # default: dev
  memorySize: 256
  timeout: 25
  environment:
    NODE_OPTIONS: "--enable-source-maps"
    NODE_ENV: ${sls:stage}          # 'dev'
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}   # ← la inyecta el workflow
  httpApi:
    cors:
      allowedOrigins: ["*"]
      allowedHeaders: ["*"]
      allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
      allowCredentials: false

package:
  individually: false
  patterns:
    - "!**/*"
    - dist/lambda.cjs               # bundle generado por build:lambda

functions:
  api:
    name: dba-api-${sls:stage}
    description: "@dba/server Express on Lambda via serverless-http"
    handler: dist/lambda.handler
    runtime: nodejs20.x
    architecture: arm64
    memorySize: 256
    timeout: 25
    events:
      - httpApi:
          method: ANY
          path: /{proxy+}
      - httpApi:
          method: GET
          path: /health

plugins: []

custom:
  # Build con esbuild se hace fuera (npm run build:lambda)
