name: Deploy Backend to Lambda (Serverless)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "packages/server/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/server
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            packages/shared/package-lock.json
            packages/server/package-lock.json

      - name: Install (root)
        run: npm ci --ignore-scripts
        working-directory: .

      - name: Build shared (optional)
        run: npm run -w @dba/shared build || true
        working-directory: .

      - name: Install Serverless CLI (v3)
        run: npm i -g serverless@3

      - name: Check Serverless version
        run: serverless --version

      - name: Build Lambda bundle
        run: npm run build:lambda

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::397348202466:role/GitHubOIDC-ServerlessDeploy
          aws-region: sa-east-1
          role-session-name: github-actions-dba

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Deploy (prod)
        run: serverless deploy --stage prod
