name: Deploy Backend to Lambda (Serverless) — DEV

on:
  workflow_dispatch:
  push:
    branches: [ main ]                     # ajusta si usas otra rama
    paths:
      - "packages/server/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/server
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            packages/shared/package-lock.json
            packages/server/package-lock.json

      - name: Install (root)
        run: npm ci --ignore-scripts
        working-directory: .

      - name: Build shared (optional)
        run: npm run -w @dba/shared build || true
        working-directory: .

      - name: Install Serverless CLI (v3)
        run: npm i -g serverless@3

      - name: Build Lambda bundle
        run: npm run build:lambda

      # 1) Credenciales OIDC (rol en tu cuenta 397348202466)
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::397348202466:role/GitHubOIDC-ServerlessDeploy
          aws-region: sa-east-1
          role-session-name: github-actions-dba

      # 2) Leer SSM DEV y exportar al entorno para Serverless
      - name: Read OPENAI_API_KEY from SSM (dev)
        run: |
          VALUE=$(aws ssm get-parameter \
            --name "/dba/dev/OPENAI_API_KEY" \
            --with-decryption \
            --region sa-east-1 \
            --query "Parameter.Value" \
            --output text)
          if [ -z "$VALUE" ] || [ "$VALUE" = "None" ]; then
            echo "::error::No se pudo leer /dba/dev/OPENAI_API_KEY en sa-east-1"
            exit 1
          fi
          echo "OPENAI_API_KEY=$VALUE" >> $GITHUB_ENV

      # (Opcional) Chequeo: no imprime el secreto, solo longitud
      - name: Check OPENAI_API_KEY is set
        run: |
          echo "OPENAI_API_KEY length: ${#OPENAI_API_KEY}"
          test -n "$OPENAI_API_KEY"

      # 3) Deploy a DEV (sa-east-1)
      - name: Deploy (dev)
        run: serverless deploy --stage dev
