name: Deploy Web to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Config recomendado por GitHub Pages
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json
            **/pnpm-lock.yaml
            **/yarn.lock

      - name: Install (root)
        run: npm ci

      - name: Build shared
        run: npm run -w @dba/shared build

      - name: Build web
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          BASE_PATH: /${{ github.event.repository.name }}/
        run: npm run -w @dba/web build

      - name: Check VITE_API_URL is set
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: test -n "$VITE_API_URL"

      # Utilidades SPA y .nojekyll (opcional pero útil)
      - name: Add .nojekyll and SPA 404
        run: |
          touch packages/web/dist/.nojekyll
          if [ ! -f packages/web/dist/404.html ] && [ -f packages/web/dist/index.html ]; then
            cp packages/web/dist/index.html packages/web/dist/404.html
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/web/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
