name: Deploy Web to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Build web
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          BASE_PATH: /${{ github.event.repository.name }}/
        run: npm run -w @dba/web build
      - name: Check VITE_API_URL is set
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: test -n "$VITE_API_URL"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/web/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
